// flow-typed signature: 2833ab73640c61823023e268991267d0
// flow-typed version: <<STUB>>/@fortawesome/pro-duotone-svg-icons_v5.13.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/pro-duotone-svg-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/pro-duotone-svg-icons' {
  declare module.exports: any;
}
