// flow-typed signature: dd2b4363e4d0cbf4ec268f9122fc3afc
// flow-typed version: <<STUB>>/i18next-browser-languagedetector_v6.0.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18next-browser-languagedetector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18next-browser-languagedetector' {
  declare module.exports: any;
}
