// flow-typed signature: ac1dbcdb0a3a9866b7343fe6ba035e66
// flow-typed version: <<STUB>>/i18next-http-backend_v1.1.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18next-http-backend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18next-http-backend' {
  declare module.exports: any;
}
