// flow-typed signature: ce456bbd9a731db4b9183bdad10bac81
// flow-typed version: <<STUB>>/lattice-fabricate_v0.19.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lattice-fabricate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lattice-fabricate' {
  declare module.exports: any;
}
