// flow-typed signature: 77c52ea1bf6fa78d56a0998b2748ebb1
// flow-typed version: <<STUB>>/match-all_v1.2.6/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'match-all'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'match-all' {
  declare module.exports: any;
}
