// flow-typed signature: c4c719300f012f69e740dec83f488d31
// flow-typed version: <<STUB>>/papaparse_v5.2.0/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'papaparse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'papaparse' {
  declare module.exports: any;
}
