// flow-typed signature: bd6a87e3275f70423e828263529aab60
// flow-typed version: <<STUB>>/react-i18next_v11.8.10/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-i18next'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-i18next' {
  declare module.exports: any;
}
