// flow-typed signature: 890906f303779ae391ac7108ca28d21b
// flow-typed version: <<STUB>>/rrule_v2.6.4/flow_v0.125.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rrule'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rrule' {
  declare module.exports: any;
}
