// flow-typed signature: 1a007c1a81e9db104220d04666ffd688
// flow-typed version: <<STUB>>/@material-ui/core_v4.11.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

declare module '@material-ui/core/LinearProgress' {
  declare module.exports: any;
}

declare module '@material-ui/core/styles' {
  declare module.exports: any;
}
