// flow-typed signature: 87e15b746d9bd08d08fb2bb8927ec883
// flow-typed version: <<STUB>>/@nivo/core_v0.74.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nivo/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nivo/core' {
  declare module.exports: any;
}
