// flow-typed signature: 1c9e136f4b879fdddafa79cb7ad0817c
// flow-typed version: <<STUB>>/@nivo/line_v0.74.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nivo/line'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nivo/line' {
  declare module.exports: any;
}
