// flow-typed signature: 727c0edc36e6ba0e317753c047019706
// flow-typed version: <<STUB>>/@nivo/tooltip_v0.74.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nivo/tooltip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nivo/tooltip' {
  declare module.exports: any;
}
