// Guards generated contract modules against hand edits when Methodic's source
// generators are unavailable in this standalone checkout. Freshness against the
// canonical sources remains enforced by Methodic's domain-contract guardrail.
import { createHash } from 'node:crypto';
import { resolve } from 'node:path';

interface GeneratedModuleExpectation {
  provenance: RegExp;
  requiredExports: readonly string[];
}

function verifyGeneratedModule(path: string, text: string, expectation: GeneratedModuleExpectation): string[] {
  const errors: string[] = [];
  if (!expectation.provenance.test(text)) {
    errors.push('missing generator provenance header');
  }
  if (!/^\/\/ Source-SHA256: [0-9a-f]{64}$/m.test(text)) {
    errors.push('missing Source-SHA256 header (file was hand-edited or truncated)');
  }
  for (const requiredExport of expectation.requiredExports) {
    if (!text.includes(`export const ${requiredExport}`)) {
      errors.push(`missing expected generated export ${requiredExport}`);
    }
  }

  const marker = '// Do not edit by hand.\n';
  const markerIndex = text.indexOf(marker);
  if (markerIndex === -1) {
    errors.push('missing do-not-edit marker');
  }

  const contentMatch = text.match(/^\/\/ Content-SHA256: ([0-9a-f]{64})$/m);
  if (!contentMatch) {
    errors.push('missing Content-SHA256 header (regenerate with the current generator)');
  } else if (markerIndex !== -1) {
    const actual = createHash('sha256')
      .update(text.slice(markerIndex + marker.length), 'utf-8')
      .digest('hex');
    if (actual !== contentMatch[1]) {
      errors.push(`Content-SHA256 mismatch: header says ${contentMatch[1]}, body hashes to ${actual}`);
    }
  }

  return errors.map((error) => `${path}: ${error}`);
}

const generatedModules = [
  {
    path: resolve(import.meta.dir, '../src/modern/generated/chronicle-contracts.ts'),
    expectation: {
      provenance:
        /^\/\/ Generated by scripts\/generate-chronicle-contracts\.py from ontology\/chronicle\.linkml\.yaml\./m,
      requiredExports: ['PARTICIPATION_STATUSES'],
    },
  },
  {
    path: resolve(import.meta.dir, '../src/modern/generated/chronicle-payload-contracts.generated.ts'),
    expectation: {
      provenance:
        /^\/\/ Generated by scripts\/generate-chronicle-payload-contracts\.py from chronicle-api and chronicle-models fixtures\./m,
      requiredExports: ['PAYLOAD_FIXTURE_REGISTRY', 'PAYLOAD_FIXTURES'],
    },
  },
] as const;

const errors: string[] = [];
for (const generatedModule of generatedModules) {
  const text = await Bun.file(generatedModule.path).text();
  errors.push(...verifyGeneratedModule(generatedModule.path, text, generatedModule.expectation));
}

if (errors.length > 0) {
  console.error('check:domain-contracts FAILED for generated Chronicle contracts');
  for (const error of errors) {
    console.error(`  - ${error}`);
  }
  console.error('Regenerate via Methodic contract generators');
  process.exit(1);
}

console.log('check:domain-contracts OK: generated domain and payload contracts carry valid integrity headers');
