#!/usr/bin/env bash
# Opens or updates a 'freshness:bun' issue with the bun outdated report.
set -euo pipefail

report="${1:-/tmp/bun-outdated.txt}"
if [ ! -f "$report" ]; then
    echo "ERROR: report not found: $report"
    exit 1
fi

repo="${REPO:-uzaira0/chronicle-web}"
title="freshness:bun — week of $(date -u +%Y-%m-%d)"

body=$(cat <<MARKDOWN
# Bun Dependency Freshness — week of $(date -u +%Y-%m-%d)

Auto-generated by \`.github/workflows/freshness-bun.yml\`.

## Outdated packages

\`\`\`
$(cat "$report")
\`\`\`

## What to do

- **Patch + minor**: dependabot auto-merge will handle these on its next run.
- **Major**: needs human review. Open a dedicated PR per major to keep blast radius small.

## Verifier

\`\`\`bash
cd chronicle-web && bun outdated
\`\`\`
MARKDOWN
)

existing=$(gh issue list --repo "$repo" --label "freshness:bun" --state open \
    --json number --jq '.[0].number // empty')

if [ -n "$existing" ]; then
    gh issue edit "$existing" --repo "$repo" --title "$title" --body "$body"
else
    gh label create "freshness:bun" --repo "$repo" --color "F0DB4F" \
        --description "Weekly bun dependency freshness report" 2>/dev/null || true
    gh issue create --repo "$repo" --title "$title" --body "$body" --label "freshness:bun"
fi
